video:
  input_path: "data/raw/autonomous_vehicle_footage.mp4"
  output_folder: "data/processed/frames"
  frame_interval: 30  # Extract every 30th frame

labeling:
  model: "gpt-4-vision-preview"
  output_file: "data/labeled/labeled_data.json"
  batch_size: 10

dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1